import { Coordinate } from "./coordinate.js";
export function DOM() {
  function createElements(element, quantity = 10, callbackFn) {
    const nodeArray = [];
    for (let counter = 0; counter < quantity; counter++) {
      const currentElement = document.createElement(element);
      if (callbackFn) callbackFn(currentElement);
      nodeArray.push(currentElement);
    }
    return nodeArray;
  }

  function createGameboard(callbackFn) {
    const gameboardNodes = createElements("div", 100, callbackFn);
    const coordinateNodes = Coordinate().set(gameboardNodes);
    return coordinateNodes;
  }

  function gameboardSettings(element) {
    element.classList.add("square");
  }

  function receiveAttack(element, result) {
    if (result == "hit") element.classList.add("hit");
    if (result == "miss") element.classList.add("miss");
  }
  // stern: back of boat
  // bow: front of boat
  function placeShip(elements) {
    let orientation = Coordinate().getOrientation(elements);
    for (let index = 0; index < elements.length; index++) {
      if (index == 0) elements[index].classList.add("stern");
      if (index == elements.length - 1) elements[index].classList.add("bow");
      elements[index].classList.add(orientation);
      elements[index].classList.add("ship");
    }
  }

  function getShipElements(coordinates, player) {
    const shipElements = [];
    for (let index = 0; index < coordinates.length; index++) {
      const currentCoordinate = coordinates[index];
      const currentShipElement = document.querySelector(
        `#${player} div[data-coordinate='${currentCoordinate}']`
      );
      shipElements.push(currentShipElement);
    }
    return shipElements;
  }

  // render out ships
  function renderShips(shipCoordinates, player) {
    shipCoordinates.forEach((coordinate) => {
      placeShip(getShipElements(coordinate, player));
    });
    //apply placeSHip func to each set of coordinates
  }

  function renderResultsOfAttack(
    coordinates = [],
    className,
    player = "player1"
  ) {
    for (let index = 0; index < coordinates.length; index++) {
      const currentCoordinate = coordinates[index];
      const square = document.querySelector(
        `#${player} div[data-coordinate='${currentCoordinate}']`
      );
      if (!square.classList.contains(`${className}`))
        square.classList.add(`${className}`);
    }
  }

  function clearResults(className, player) {
    const elements = document.querySelectorAll(`#${player} ${className}`);
    for (let index = 0; index < elements.length; index++) {
      const currentElement = elements[index];
      currentElement.classList.remove(`${className}`);
    }
  }

  function announce(message = "Player 1's turn") {
    document.querySelector(".announcements").textContent = message;
  }

  function renderPlayerGameboard(playerShips, player) {
    const gameboard = document.querySelector("#" + player + ".gameboard");
    gameboard.append(...createGameboard(gameboardSettings));
    renderShips(playerShips, player);
  }

  function renderModelShips(player) {
    const shipSection = document.querySelector("#" + player + ".ships");
    const shipSizesClass = ["size-2", "size-3#2", "size-3", "size-4", "size-5"];
    const shipContainers = createElements("div", 5, (container) => {
      container.classList.add("model-ship-container");
      container.classList.add(shipSizesClass.pop());
    });
    const shipSizes = [5, 4, 3, 3, 2];
    for (let i = 0; i < 5; i++) {
      // adds model ship square class to each ship in a container
      shipContainers[i].append(
        ...createElements("div", shipSizes[i], (ship) =>
          ship.classList.add("model-ship-square")
        )
      );
      shipSection.append(shipContainers[i]);
    }
  }

  function initializeGame() {
    const main = document.querySelector("main");
    main.innerHTML = `
      <div id="player1" class="section">
        <div class="ships" id="player1"></div>
        <div class="gameboard" id="player1"></div>
      </div>
      <div id="player2" class="section">
        <div class="gameboard" id="player2"></div>
        <div class="ships" id="player2"></div>
      </div> `;
  }

  // todo
  // create gameboard to get player coordinates
  // I think if each rendered ship had classes associated with them, it would be easier to find
  // click start -> creates gameboard with ships placed
  // click on ship -> find other divs with same ship class and select them as current ship
  // click on arrow -> change x or y value depending on the arrow direction
  // click on rotate -> use the first coordinate as an anchor, if the ship is vertical, change coordinates from change in y to change in x relative to anchors position, if the ship is horizontal, change coordinates from change in x to change in y relative to anchors position.
  // displays ship to be placed while hovering
  // will then save ships to player1 in storage
  // player2 ships will be autogenerated at random
  // then remove the gameboard
  // display both gameboards
  // add shake transition, using keyframes, if hit
  // firing sounds upon clicking a square, water sounds on miss, explosion sounds on hit
  return {
    createGameboard,
    renderResultsOfAttack,
    clearResults,
    renderPlayerGameboard,
    placeShip,
    receiveAttack,
    announce,
    renderModelShips,
    initializeGame,
  };
}
